##ndarray数组创建

In [3]:
import numpy as np
from skimage.util import dtype

In [5]:
#基础创建方法
arr = np.array([1,2,3])
print(arr.ndim)  #属性
print(arr)

1
[1 2 3]


In [7]:
#copy
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[1 2 3]
[8 2 3]
[1 2 3]


In [10]:
#预定义形状
#全0  全1  未初始化
#全0
arr = np.zeros((2,3),dtype=int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [13]:
arr = np.zeros((2,),dtype=int)
print(arr)

[0 0]


In [15]:
#全1
arr = np.ones((5,8),dtype=int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [16]:
#未初始化
arr = np.empty((5,8))
print(arr)

[[0.00000000e+000 1.21958079e-311 6.95238749e-310 2.52961611e-321
  6.36598761e-314 6.36598737e-311 6.36598737e-311 0.00000000e+000]
 [2.12199579e-314 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 1.21958079e-311]
 [0.00000000e+000 4.94065646e-324 0.00000000e+000 1.36656529e-311
  0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 4.94065646e-324 4.44659081e-323
  0.00000000e+000 1.21961203e-311 1.21961204e-311 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 0.00000000e+000 0.00000000e+000 1.21958079e-311]]


In [17]:
arr = np.full((3,4),2026)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [18]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
arr1 = np.ones_like(arr)
print(arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
arr1 = np.empty_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [21]:
#等差数列
arr = np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [25]:
#等间隔数列
arr = np.linspace(0,100,5)
print(arr)

[  0.  25.  50.  75. 100.]


In [29]:
arr = np.linspace(0,101,5,dtype=int)
print(arr)
arr = np.arange(0,101,25)
print(arr)

[  0  25  50  75 101]
[  0  25  50  75 100]


In [33]:
#对数间隔数列
arr = np.logspace(0,4,2,base=2)
print(arr)

[ 1. 16.]


In [37]:
#特殊矩阵
#单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [39]:
#对角矩阵：主对角线上非零的0，其他的数字为0
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [46]:
#随机数组的生成
#生成0-1之间的随机浮点数（均匀分布）
arr = np.random.randn(3,4)
print(arr)

[[ 1.61304876  0.89579879 -0.35545122 -2.17450402]
 [ 0.20351546 -0.90914073 -0.39991147  0.74625705]
 [-0.80297527 -0.28055737  0.39328181 -1.14983547]]


In [47]:
#生成指定范围区间的随机浮点数
arr = np.random.uniform(3,8,(3,4))
print(arr)

[[7.92183009 7.15397697 7.24452618 3.12004657]
 [6.69156503 4.38081749 5.18816951 6.71800125]
 [3.55022667 5.35897902 3.94103994 5.54832986]]


In [48]:
#生成指定范围区间的随机整数
arr = np.random.randint(3,30,(3,4))
print(arr)

[[25 27  3  7]
 [27 18  5 15]
 [18  8 20 26]]


In [50]:
#生成随机数列（正态分布）
#两边小，中间大
arr = np.random.randn(3,4)
print(arr)

[[-1.97385896  0.74814876 -0.70524915 -0.88879375]
 [-0.58607984 -0.36622926  0.20946607  0.86229388]
 [-0.7284226  -2.58134131  0.68975255  0.14514279]]


In [65]:
#设置随机种子
np.random.seed(200)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[1 5 8 7 9]
 [2 8 4 2 8]]
